name: Runner

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "data.json" ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Run
        env:
          data: ${{ secrets.DATA }}
        run: |
          ./gradlew run
          
          git config --global user.name 'ithome-watcher'
          git config --global user.email 'ithome-watcher@users.noreply.github.com'
          git add data.json
          git commit -am "Automated report" || true
          git push || true