name: Runner

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "data.json", "ui-data.json" ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Run
        env:
          data: ${{ secrets.DATA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          ./gradlew run
          
          git config --global user.name 'ithome-watcher'
          git config --global user.email 'ithome-watcher@users.noreply.github.com'
          git add data.json ui-data.json
          git commit -am "Automated report" || true
          git push || true
          
          aws s3 cp data.json s3://ithome-ironman-watcher/2022/data.json --acl public-read
          aws s3 cp ui-data.json s3://ithome-ironman-watcher/2022v2/ui-data.json --acl public-read