name: Runner

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "data.json", "ui-data.json" ]
  schedule:
    - cron: '17 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export ithome_crawler_s3_bucket=ithome-ironman-watcher
          export ithome_crawler_env=production
          
          ./gradlew installDist
          ./build/install/ithome-ironman/bin/ithome-ironman
          
          aws s3 cp s3://ithome-ironman-watcher/2024/ui-data.json s3://ironman-2024.qrtt1.io/ui-data.json
          
